In [9]:
import pandas as pd
import pandas_read_xml as pdx

In [13]:
green_areas = pd.read_csv('https://raw.githubusercontent.com/SowmyaMadala/WDL-Stage4/main/Data/Attracting%20Population/WDL_Green_Areas_Dataset_V1.txt', 
                          sep ="|", 
                          encoding ="latin-1").rename(columns = {'Number of Museums in influence area' : 'no_of_museums',
                                                                 'Number of parking lots in influence area' : 'no_of_parking_lots',
                                                                'Number of tourist attractions in influence area': 'no_of_tourist_attractions', 
                                                                'Green Zones Daily Average Demand':'gz_daily_avg_demand',
                                                                'Daily average of people in influence area': 'daily_avg_people',
                                                                'Number of buildings in influence area' : 'no_of_buildings',
                                                                'Number of families in influence area': 'no_of_families',
                                                                'Number of people resident in influence area' : 'no_of_people_resident'
                                                                })

green_areas.shape, green_areas.dtypes

((128, 14),
 Green_Zone_name               object
 no_of_museums                  int64
 no_of_parking_lots             int64
 no_of_tourist_attractions      int64
 gz_daily_avg_demand          float64
 Resident                       int64
 daily_avg_people             float64
 no_of_buildings                int64
 no_of_families                 int64
 no_of_people_resident          int64
 perc_senior_pop              float64
 perc_pop_until_19_yo         float64
 POINT_X                      float64
 POINT_Y                      float64
 dtype: object)

In [14]:
green_areas

,Green_Zone_name,no_of_museums,no_of_parking_lots,no_of_tourist_attractions,gz_daily_avg_demand,Resident,daily_avg_people,no_of_buildings,no_of_families,no_of_people_resident,perc_senior_pop,perc_pop_until_19_yo,POINT_X,POINT_Y
0,ESPAÇO JOGO E RECREIO HOMEM DO LEME,5,28,30,3.728677,1,17780.803014,4783,15352,38012,0.195123,0.196017,-8.68415,41.16001
1,ESPAÇO JOGO E RECREIO HOMEM DO LEME,5,28,30,3.728677,0,45787.629298,4783,15352,38012,0.195123,0.196017,-8.68415,41.16001
2,JARDIM AFONSO DE ALBUQUERQUE,93,129,78,10.259113,0,42877.741202,1775,17185,41163,0.161747,0.204917,-9.19949,38.69674
3,JARDIM AFONSO DE ALBUQUERQUE,93,129,78,10.259113,1,17497.825376,1775,17185,41163,0.161747,0.204917,-9.19949,38.69674
4,JARDIM ALAMEDA CIDADE UNIVERSITÁRIA,8,23,4,47.347816,0,42877.741202,1775,17185,41163,0.161747,0.204917,-9.15757,38.75294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,PRAÇA NOVE DE ABRIL,0,0,0,15.707606,1,19714.378546,7789,19185,44298,0.236941,0.154770,-8.61187,41.17106
124,QUINTA DAS CONCHAS,0,0,0,3.129490,0,42877.741202,1775,17185,41163,0.161747,0.204917,-9.15520,38.77121
125,QUINTA DAS CONCHAS,0,0,0,3.129490,1,17497.825376,1775,17185,41163,0.161747,0.204917,-9.15520,38.77121
126,QUINTA DOS LILÁSES,0,0,0,103.891288,0,42877.741202,1775,17185,41163,0.161747,0.204917,-9.15950,38.76993
127,QUINTA DOS LILÁSES,0,0,0,103.891288,1,17497.825376,1775,17185,41163,0.161747,0.204917,-9.15950,38.76993

In [11]:
freguesias = pdx.read_xml('raw_data/Freguesiasdadosgerais.xml')

In [12]:
freguesias

                                                feed
0  {'@xml:base': 'http://servico.dados.gov.pt/v1/...